### ISSUE TITLE
Add a World menu to let users give feedback

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Spy2#3]
Maybe commonalities between Roassal and Spy can be defined on some point.

**Comment by akevalion** [comment]
There is a new menu item to chat with us in roassal channel in pharo server.
![image](https://user-images.githubusercontent.com/10532890/81993881-a5006400-9614-11ea-92e8-347b8dd1fcdd.png)

**Comment by bergel** [comment]
Super!
