### ISSUE TITLE
Integration of Dark theme in Hapao is not great

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Spy2#5]
previously hovering over a class box changed the name's color so it is visible
![unknown](https://user-images.githubusercontent.com/393742/27042682-b911593e-4f65-11e7-946d-d25ed8a184af.png)

but with dark theme it's not so good

![unknown-1](https://user-images.githubusercontent.com/393742/27042693-c1b3419c-4f65-11e7-8781-4956fe3990d7.png)

**Comment by akevalion** [comment]
I have updated spy2 with the dark theme

![image](https://user-images.githubusercontent.com/10532890/60688554-ee741480-9e83-11e9-9f49-1c2b9c8a3f65.png)

**Comment by tinchodias** [comment]
Very nice, IMO. Maybe the dark red doesn't contrast well with the background color.

**Comment by akevalion** [comment]
Is there any update for these issue?

**Comment by bergel** [comment]
Great work!
