### ISSUE TITLE
Bug when restarting in Hapao

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Spy2#6]
Here is how to reproduce the error:

1 - Select `Hapao @ Class...`
2 - Enter `RTView`
3 - Click on `Hapao again` in the new open window. Clicking on this should run Hapao again on the class `RTView`.

**Comment by akevalion** [comment]
Fixed in version Spy2-Hapao-Core-akevalion.17

**Comment by bergel** [comment]
Works correctly! Thanks!
