### ISSUE TITLE
Should work with the last version of Roassal3

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Spy2#7]

**Comment by akevalion** [comment]
We are green now in spy2

![image](https://user-images.githubusercontent.com/10532890/81993995-e3961e80-9614-11ea-9247-2cd8825163d7.png)

![image](https://user-images.githubusercontent.com/10532890/81994007-edb81d00-9614-11ea-8080-aff8dee9fc5b.png)

![image](https://user-images.githubusercontent.com/10532890/81994024-f7418500-9614-11ea-8f35-4bc50f3acf92.png)

**Comment by akevalion** [comment]
Spy2 now only depends on Roassal3-Core
